channels:
- conda-forge
- nodefaults
- bioconda
- r
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- any2fasta=0.4.2
- argtable2=2.13
- biopython=1.81
- blast=2.14.0
- blast-legacy=2.2.26
- brotli=1.0.9
- brotli-bin=1.0.9
- bzip2=1.0.8
- c-ares=1.19.1
- ca-certificates=2023.5.7
- certifi=2023.5.7
- charset-normalizer=3.1.0
- clustalo=1.2.4
- clustalw=2.1
- csvtk=0.31.1
- curl=7.87.0
- entrez-direct=16.2
- expat=2.5.0
- gettext=0.21.1
- idna=3.4
- keyutils=1.6.1
- krb5=1.20.1
- ld_impl_linux-64=2.40
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libcurl=7.87.0
- libdb=6.2.32
- libedit=3.1.20191231
- libev=4.33
- libexpat=2.5.0
- libffi=3.3
- libgcc-ng=13.1.0
- libgfortran=3.0.0
- libgfortran-ng=13.1.0
- libgfortran5=13.1.0
- libgomp=13.1.0
- libidn2=2.3.4
- liblapack=3.9.0
- libnghttp2=1.51.0
- libnsl=2.0.0
- libopenblas=0.3.21
- libsqlite=3.42.0
- libssh2=1.10.0
- libstdcxx-ng=13.1.0
- libunistring=0.9.10
- libzlib=1.2.13
- mafft=7.525
- mlst=2.23.0
- muscle=5.1
- ncurses=6.3
- ngmaster=1.0.0
- numpy=1.24.3
- openssl=1.1.1u
- paml=4.10.6
- parallel=20230522
- pcre=8.45
- perl=5.32.1
- perl-algorithm-diff=1.201
- perl-archive-tar=2.40
- perl-base=2.23
- perl-bio-asn1-entrezgene=1.73
- perl-bio-coordinate=1.007001
- perl-bio-featureio=1.6.905
- perl-bio-samtools=1.43
- perl-bio-searchio-hmmer=1.7.3
- perl-bio-tools-phylo-paml=1.7.3
- perl-bio-tools-run-alignment-clustalw=1.7.4
- perl-bio-tools-run-alignment-tcoffee=1.7.4
- perl-bioperl=1.7.8
- perl-bioperl-core=1.7.8
- perl-bioperl-run=1.007003
- perl-business-isbn=3.007
- perl-business-isbn-data=20210112.006
- perl-carp=1.50
- perl-class-data-inheritable=0.09
- perl-class-method-modifiers=2.13
- perl-common-sense=3.75
- perl-compress-raw-bzip2=2.201
- perl-compress-raw-zlib=2.202
- perl-constant=1.33
- perl-data-dumper=2.183
- perl-db_file=1.858
- perl-devel-stacktrace=2.04
- perl-digest-hmac=1.04
- perl-digest-md5=2.58
- perl-encode=3.19
- perl-encode-locale=1.05
- perl-exception-class=1.45
- perl-exporter=5.74
- perl-exporter-tiny=1.002002
- perl-extutils-makemaker=7.70
- perl-file-listing=6.15
- perl-file-slurp-tiny=0.004
- perl-file-sort=1.01
- perl-file-spec=3.48_01
- perl-file-which=1.24
- perl-getopt-long=2.54
- perl-html-parser=3.81
- perl-html-tagset=3.20
- perl-http-cookies=6.10
- perl-http-daemon=6.16
- perl-http-date=6.05
- perl-http-message=6.36
- perl-http-negotiate=6.01
- perl-inc-latest=0.500
- perl-io-compress=2.201
- perl-io-html=1.004
- perl-io-socket-ssl=2.075
- perl-io-string=1.08
- perl-io-tty=1.16
- perl-io-zlib=1.14
- perl-ipc-run=20200505.0
- perl-json=4.10
- perl-json-xs=2.34
- perl-libwww-perl=6.67
- perl-libxml-perl=0.08
- perl-list-moreutils=0.430
- perl-list-moreutils-xs=0.430
- perl-lwp-mediatypes=6.04
- perl-lwp-protocol-https=6.10
- perl-mime-base64=3.16
- perl-module-build=0.4234
- perl-moo=2.005004
- perl-mozilla-ca=20211001
- perl-net-http=6.22
- perl-net-ssleay=1.92
- perl-ntlm=1.09
- perl-parent=0.241
- perl-pathtools=3.75
- perl-role-tiny=2.002004
- perl-scalar-list-utils=1.63
- perl-socket=2.027
- perl-storable=3.15
- perl-sub-quote=2.006006
- perl-sub-uplevel=0.2800
- perl-test-deep=1.130
- perl-test-differences=0.69
- perl-test-exception=0.43
- perl-test-fatal=0.016
- perl-test-most=0.38
- perl-test-requiresinternet=0.05
- perl-test-warn=0.37
- perl-test-warnings=0.031
- perl-text-diff=1.45
- perl-time-local=1.35
- perl-timedate=2.33
- perl-tree-dag_node=1.32
- perl-try-tiny=0.31
- perl-types-serialiser=1.01
- perl-uri=5.17
- perl-url-encode=0.03
- perl-www-robotrules=6.02
- perl-xml-dom=1.46
- perl-xml-dom-xpath=0.14
- perl-xml-parser=2.44_01
- perl-xml-regexp=0.04
- perl-xml-xpathengine=0.14
- pip=23.1.2
- poa=2.0
- pysocks=1.7.1
- python=3.9.0
- python_abi=3.9
- readline=8.2
- requests=2.31.0
- setuptools=67.7.2
- sqlite=3.42.0
- t-coffee=12.00.7fb08c2
- tk=8.6.12
- tzdata=2023c
- urllib3=2.0.2
- viennarna=2.5.1
- wget=1.20.3
- wheel=0.40.0
- xz=5.2.6
- zlib=1.2.13
- pip:
  - argparse==1.4.0
  - beautifulsoup4==4.12.2
  - bs4==0.0.1
  - soupsieve==2.4.1
name: ngmaster-env
