language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip install .
  - wget https://github.com/denglab/SeqSero/raw/1f84a6c7abd22c43227ce9fa0dfbda87a9f02449/libs/isPcr
  - chmod +x isPcr

# command to run tests
script:
  - echo $PATH
  - ngmaster --test
