language: python

python:
  - "3.6"

install:
  - pip install .
  - "wget https://github.com/denglab/SeqSero/raw/1f84a6c7abd22c43227ce9fa0dfbda87a9f02449/libs/isPcr"
  - chmod +x isPcr
  - export PATH="$PWD:$PATH"

script:
  - echo $PATH
  - ngmaster --version
  - ngmaster --help
  - ngmaster --test
