#!/usr/bin/env perl

use strict;
use LWP::Simple;
use File::Slurp;

my $URL = "http://www.ng-mast.net/sql";

for my $gene ('POR', 'TBPB') {
  print STDERR "Downloading $gene HTML\n";
  my $html = get("$URL/fasta.asp?allele=$gene");
  print STDERR "Parsing $gene HTML for alleles\n";
  $html =~ s/^.*<textarea name=.?concat.*?>//s;
  $html =~ s/<\/textarea>.*$//s;
  $html =~ s/&gt;/>/g;
  print STDERR "Saving result to $gene.fasta\n";
  write_file("$gene.fasta", $html);
}

print STDERR "Download ST assignments\n";
my $csv = get("$URL/st_comma.asp");
$csv =~ s/,/\t/g;
$csv =~ s/<br>/\n/gi;
my $file = "NG-MAST.tab";
print STDERR "Saving to $file\n";
write_file($file, $csv);

__DATA__

POR:

<input type=button value="Highlight All" onClick="javascript:this.form.concatenation.focus();this.form.concatenation.select();">
<br>
<textarea name="concatenation" cols="60" rows="15" >&gt;POR1
TTGAAAGGCGGCTTCGGCACCATCCGCGTCGGCAGCCTGAACAGCCCCCTGAAAAACACCGGTGCCAACGTCAATGCTTGGGAATCCGGCAAATATACCGGCGAGTTTCTGGAAATCAGCAAAATGGCCAGACAGGAACACCGCTACCTGTCCGCACGCTACGATTCTCCCGAATTTGCCGGCTTCAGCGGCAGCGTACAATACGCACCTAAAGATAATTCAGGCTCAAACGGCGAATCTTACCACGTTGGCTTGAACTACCGAAACGGCGGCTTCTTCGCACAATACGCCGGCTTGTTCCAAAGATACGGCGAAGGCACTAAAATCGAATACGATAGTCAATATTATAGTATCCCCAGCCTGTTTGTTGAAAAACTGCAAGTTCACCGTTTGGTCGGCGGTTACGACAATAATGCCCTGTACGCCTCCGTAGCCGCACAACAACAAGATGCCAAATTGTATGGAACATGGCGTGCTAATTCGCACAACT
&gt;POR2
TTGAAGGGCGGCTTCGGTACCATCCGCGCCGGTAGCC

</textarea>


<textarea name="concatenation" cols="60" rows="15" >&gt;TBPB0001
TTGAAAGGCGGCTTCGGCACCATCCGCGTCGGCAGCCTGAACAGCCCCCTGAAAAACACCGGTGCCAACGTCAATGCTTGGGAATCCGGCAAATATACCGGCGAGTTTCTGGAAATCAGCAAAATGGCCAGACAGGAACACCGCTACCTGTCCGCACGCTACGATTCTCCCGAATTTGCCGGCTTCAGCGGCAGCGTACAATACGCACCTAAAGATAATTCAGGCTCAAACGGCGAATCTTACCACGTTGGCTTGAACTACCGAAACGGCGGCTTCTTCGCACAATACGCCGGCTTGTTCCAAAGATACGGCGAAGGCACTAAAATCGAATACGATAGTCAATATTATAGTATCCCCAGCCTGTTTGTTGAAAAACTGCAAGTTCACCGTTTGGTCGGCGGTTACGACAATAATGCCCTGTACGCCTCCGTAGCCGCACAACAACAAGATGCCAAATTGTATGGAACATGGCGTGCTAATTCGCACAACT
&gt;TBBP0002
TTGAAGGGCGGCTTCGGTACCATCCGCGCCGGTAGCC

</textarea>

ST:

3145,1911,4<br>3146,1904,4<br>

